[package]
name = "data_types"
version = "0.1.0"
edition = "2021"
description = "Shared data types"

[dependencies]
influxdb_line_protocol = { path = "../influxdb_line_protocol" }
observability_deps = { path = "../observability_deps" }
ordered-float = "3"
percent-encoding = "2.1.0"
schema = { path = "../schema" }
snafu = "0.7"
sqlx = { version = "0.5", features = ["runtime-tokio-rustls", "postgres", "uuid"] }
uuid = { version = "0.8", features = ["v4"] }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies] # In alphabetical order
test_helpers = { path = "../test_helpers" }
