[package]
name = "influxdb_iox_client"
version = "0.1.0"
authors = ["Dom Dwyer <dom@itsallbroken.com>"]
edition = "2021"

[features]
default = ["flight", "format", "write_lp"]
flight = ["arrow", "arrow-flight", "arrow_util", "futures-util"]
format = ["arrow", "arrow_util"]
write_lp = ["dml", "mutable_batch_lp", "mutable_batch_pb"]

[dependencies]
# Workspace dependencies, in alphabetical order
arrow_util = { path = "../arrow_util", optional = true }
client_util = { path = "../client_util" }
dml = { path = "../dml", optional = true }
generated_types = { path = "../generated_types", default-features = false }
mutable_batch_lp = { path = "../mutable_batch_lp", optional = true }
mutable_batch_pb = { path = "../mutable_batch_pb", optional = true }
observability_deps = { path = "../observability_deps" }

# Crates.io dependencies, in alphabetical order
arrow = { version = "15.0.0", optional = true }
arrow-flight = { version = "15.0.0", optional = true }
bytes = "1.0"
futures-util = { version = "0.3", optional = true }
prost = "0.10"
rand = "0.8.3"
snafu = "0.7"
thiserror = "1.0.31"
tonic = { version = "0.7" }

[dev-dependencies] # In alphabetical order
tokio = { version = "1.19", features = ["macros", "parking_lot", "rt-multi-thread"] }
