[package]
name = "observability_deps"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2021"
description = "Observability ecosystem dependencies for InfluxDB IOx, to ensure consistent versions and unified updates"

[dependencies] # In alphabetical order
tracing = { version = "0.1", features = ["max_level_trace"] }
workspace-hack = { path = "../workspace-hack"}

[features]
default = []

# Optionally enable trace events in the release build if enabled.
release_max_level_trace = ["tracing/release_max_level_trace"]
