[package]
name = "predicate"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = { version = "15.0.0", features = ["prettyprint"] }
chrono = { version = "0.4", default-features = false }
data_types = { path = "../data_types" }
datafusion = { path = "../datafusion" }
datafusion_util = { path = "../datafusion_util" }
itertools = "0.10"
observability_deps = { path = "../observability_deps" }
query_functions = { path = "../query_functions"}
schema = { path = "../schema" }
serde_json = "1.0.81"
snafu = "0.7"
sqlparser = "0.18.0"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
test_helpers = { path = "../test_helpers" }
